### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Zefeng-Wu** [Xinglab/TideHunter#1]
Hi, I am using TideHunter to run a fastq file (~4GB),  and it gave an error with a segmentation fault and stopped after running for a while. It seemed only produce an incomplete result.  Is it caused by the software or my computer?

**Comment by yangao07** [comment]
Can you provide me some rough stats about your data?
Like number of reads, max./min. length.

Thanks!

**Comment by Zefeng-Wu** [comment]
As you said, it indeed due to the longer reads. I have solved the problem by deleting some longer reads from my fastq file,  and it worked.

**Comment by yangao07** [comment]
Thanks for your information.
Actually, do you mind uploading one read that causes the segfault?
I just want to see how the fault happens.

Thanks!

**Comment by Zefeng-Wu** [comment]
Sure, here is one of the longer read from my fastq file.

[test.fq.txt](https://github.com/Xinglab/TideHunter/files/3724331/test.fq.txt)

**Comment by yangao07** [comment]
The segfault is fixed in the latest release (v1.1).
But seems like TideHunter is not able to find any repeats from the read you provided.

Yan
