### ISSUE TITLE
Sigmoid-smoothed consensus calling error rate

### ISSUE THREAD

**Issue by Catvick26** [Xinglab/TideHunter#13]
Hi Yan,

May I check with you how the parameters of probability function are estimated? And why sigmoid function is used to calculate the error rate of the consensus? i have searched around but i couldn't find articles talking about this... Thank you!

catvick

**Comment by yangao07** [comment]
The sigmoid-smoothed function is used to make sure the probability line goes flat when the coverage is very high.
There is actually no reference for this.
Those parameters were selected to guarantee that the quality score range is 0-60 (ASCII: 33-93 with shift).

**Comment by Catvick26** [comment]
> The sigmoid-smoothed function is used to make sure the probability line goes flat when the coverage is very high. There is actually no reference for this. Those parameters were selected to guarantee that the quality score range is 0-60 (ASCII: 33-93 with shift).

I see. Thanks for you reply! :)
