### ISSUE TITLE
Tidehunter failed to produce consensus sequences

### ISSUE THREAD

**Issue by jacopoM28** [Xinglab/TideHunter#15]
Hi everyone, 

I builded Tidehunter V. 1.5.3 from source files but when I try to generate consensus sequences from a set of HiFi PacBio reads Tidehunter raise the error 'No enough sequences to perform msa'. If I only generate unit sequences it works well. Any advice?Thanks in advance.

Jacopo

**Comment by yangao07** [comment]
Hi Jacopo,

Please try out the latest v1.5.4, it should solve this problem.
It may not be available from conda now, you can install it from source or download the binary file of TideHunter.

Yan

**Comment by jacopoM28** [comment]
Thank you for the fast reply, with the new version everything work well!

**Comment by algaebrown** [comment]
Can you release v1.5.4 on conda too? Thanks

**Comment by yangao07** [comment]
Not sure why it wasn't automatically updated.
I just made the pull request, need to wait for it to be approved.

**Comment by yangao07** [comment]
The v1.5.4 in conda is updated.

**Comment by algaebrown** [comment]
Thank you!
