### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by julia-luz** [Xinglab/TideHunter#19]
Hello! 

Tidehunter exits with `Illegal instruction (core dumped)`. It creates the output file,  but it's empty. I've tried it with versions 1.5.1, 1.5.2,  1.5.3 and 1.5.4 - all installed through conda. First noticed the issue with my own data, but it still happens with the provided test data. I had it working on 1.5.3 in a different environment.

**Comment by yangao07** [comment]
Hi, have you tried intalling with `make` command?

**Comment by julia-luz** [comment]
Thank you for such a speedy reply! I was literally just done trying to install it with `git clone` - it does work, as long as you use `bin/TideHunter` to call the program. I'll see how it behaves inside my pipeline!

**Comment by yangao07** [comment]
That way, the conda installation error should the known issue in abPOA (https://github.com/yangao07/abPOA/issues/42 and https://github.com/yangao07/abPOA/issues/55). 
Usually, it happens when the machine/CPU type is old.

**Comment by julia-luz** [comment]
Interesting - indeed my server is very old. This explains why I could get it working in my personal computer but not our server despite using the same yaml file.
