### ISSUE TITLE
TideHunter v1.1 did not produce any result

### ISSUE THREAD

**Issue by Zefeng-Wu** [Xinglab/TideHunter#2]
Hi, I am using both TideHunter (v1.0) and v1.1. When I run TideHunter v1.1  on a file with nano-sequencing reads (~3GB), it seemed to come to a deadlock and no result was produced after several hours, while I changed to TideHunter v1.0, it can produced some results, but it stopped with a segmental error due to the longer reads.

**Comment by yangao07** [comment]
The main update of v1.1 is "Fix a segfault in consensus generating step".

**Comment by yangao07** [comment]
Hi,

Thanks for trying TideHunter!
The main update of v1.1 is "Fix a segfault in consensus generating step".

Not sure why there was no result generated.
What are the input reads? Are they RCA-based long-reads?
Do you mind uploading some reads? Maybe I will have some thoughts then.

Thanks!
Yan

**Comment by Zefeng-Wu** [comment]
Hi Yan,


Thank you for your response. Yes, our data was from RCA-based long reads. I have attached some long reads in this email, named "test.fa.txt". I think the problem is still caused by the sequence length which I came up previously. I have made a test, 50kb may be the limitation.


Best,


Zefeng


------------------ 原始邮件 ------------------
发件人: "Yan Gao"<notifications@github.com>;
发送时间: 2019年11月3日(星期天) 晚上6:39
收件人: "Xinglab/TideHunter"<TideHunter@noreply.github.com>;
抄送: "武泽峰"<835102330@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Xinglab/TideHunter] TideHunter v1.1 did not produce any result(#2)




Hi,
 
Thanks for trying TideHunter!
 The main update of v1.1 is "Fix a segfault in consensus generating step".
 
Not sure why there was no result generated.
 What are the input reads? Are they RCA-based long-reads?
 Do you mind uploading some reads? Maybe I will have some thoughts then.
 
Thanks!
 Yan

**Comment by yangao07** [comment]
The length might be the potential reason.
I did not receive the "test.fa.txt" in the email.
Actually you can upload here in the issue's comment.

**Comment by Zefeng-Wu** [comment]
Well, here are some examples of our nano-sequences , https://github.com/Zefeng-Wu/Bioinformatics_softwares/blob/master/test.fa.txt

**Comment by yangao07** [comment]
Thanks for your data!
Please try the latest version, v1.1.1 (https://github.com/yangao07/TideHunter/releases/download/v1.1.1/TideHunter-v1.1.1_x64-linux.tar.gz).
Let me know if it works or not.

Thanks!
Yan

**Comment by Zefeng-Wu** [comment]
TideHunter  all.fastq -o 2cons.fa
error:  Illegal instruction (core dumped)

**Comment by yangao07** [comment]
Not sure where the error comes from.
Did you use the pre-built binary file?
My guess is your machine may not support AVX2 instruction.
The default binary `TideHunter` in the release package is `TideHunter-avx2-256bits`.
You can try `TideHunter-sse41-128bits` or `TideHunter-sse2-128bits`,
Or you can just build it from the source file: https://github.com/yangao07/TideHunter/releases/download/v1.1.1/TideHunter-v1.1.1.tar.gz

**Comment by Zefeng-Wu** [comment]
Yeah, I recompiled it from the source file you gave me, and it succeeded.  However, I noticed that there was a slight difference between the result from v1.0 and v1.1.1 using the same fastq file, mainly the number of the identified tandem repeat. The latter identified more repeat. So, which is more confidential?

**Comment by yangao07** [comment]
I suggest you go with v1.1.1.
