### ISSUE TITLE
Is it possible to install in an conda environment

### ISSUE THREAD

**Issue by zztin** [Xinglab/TideHunter#4]
I would like to run this on a hpc. It would be very helpful if the program can be managed with conda environment. Would like to know if this is possible! Thanks!

**Comment by yangao07** [comment]
Thanks for your interest in TideHunter.
I will try to get it to work with conda, but it may take some time.

For now, maybe you can first try install it with the source file, or directly use the pre-built binary file:
https://github.com/yangao07/TideHunter/releases

Yan

**Comment by zztin** [comment]
Sounds good! Thanks :)

**Comment by yangao07** [comment]
I have set it up with bioconda. 
It is now waiting to be approved.
Will let you know when it is ready!

Yan

**Comment by zztin** [comment]
That's great to hear! Thanks!

**Comment by yangao07** [comment]
Hi @zztin , please try to install TideHunter via:
```
conda install -c bioconda tidehunter 
```
Let me know if it works!

**Comment by yangao07** [comment]
Hi @zztin , please try to install TideHunter via:
```
conda install -c bioconda tidehunter 
```
Let me know if it works!

**Comment by zztin** [comment]
Hi,
It works on a linux machine, and on a mac machine. While qsub to a hpc
compute node, it fails. I haven’t figured out what is the problem.
I faced same issue ( worked on hpc head node/interactive compute node, but
didn’t work when submitted to a compute node) when using TideHunter with
local installation on the hpc.
Currently i hindered this problem by using a singularity container.

If you have some ideas where the problem may lies, let me know.

Best,

**Comment by yangao07** [comment]
Do you have any error message when submitting jobs to nodes?
Did your qsub comand include "-V"?

**Comment by zztin** [comment]
Hi Yan Gao, 

I did include -V in the submission :) 
Sorry for the delayed reply. I have some time today to try it out again. It worked now! I was not able to reproduce the error I had. Currently, both local installation and conda installation works with sge submission. Thank you!
