### ISSUE TITLE
[simd_abpoa_align_sequence_to_graph] Error in cg_backtrack. (4)

### ISSUE THREAD

**Issue by zztin** [Xinglab/TideHunter#7]
Hi, 

I received this error code: 
[simd_abpoa_align_sequence_to_graph] Error in cg_backtrack. (4)

for a few specific read that fails some runs. I tried on Linux machine
- git clone repo, make
- download TideHunter-v1.4.2 and build from source
- download TideHunter-v1.4.2 and build from source in a singularity image

the failed sequence is provided as a txt file as attachment.

I appreciate your time in looking into this! I am also wondering if it is possible to implement
-  excluding the failed reads and keep running
- include the failed read name/ sequence in std-err file or another output file.
[test.txt](https://github.com/Xinglab/TideHunter/files/5409735/test.txt)

Best,
Liting

**Comment by zztin** [comment]
The three methods all failed with the same error. The singularity recipe I used to build TideHunter is 
[tidehunter_singularity_recipe.txt](https://github.com/Xinglab/TideHunter/files/5409770/tidehunter_singularity_recipe.txt)

**Comment by yangao07** [comment]
Hi Liting,

This is a known bug in abPOA (https://github.com/yangao07/abPOA/issues/9).
I have fixed it, but haven't updated it in TideHuner.
Will do that soon, please try it later.

Yan

**Comment by yangao07** [comment]
This one should be fixed by the latest version (v1.4.3). Please try it out. 
The conda may take some time to update.

**Comment by zztin** [comment]
It worked (also from conda installation).
