### ISSUE TITLE
Unit-seq

### ISSUE THREAD

**Issue by liza-alpinia** [Xinglab/TideHunter#8]
Hi,
I received this error code:
invalid option -- 'u' 
In the old version file with unit sequences of each tandem repeat were available 
Could you tell me, how I may get this file in a new version if at all possible?

**Comment by yangao07** [comment]
Can you please post here your full commands and the version you used?

**Comment by liza-alpinia** [comment]
Good day
I found a mistake. It turned out that the old version of the tool is running because of an internal error at the server.  But thank you for your prompt reply

**Comment by yangao07** [comment]
OK, so I will just close this issue.
