### ISSUE TITLE
Skipping gap or ambiguous symbol N

### ISSUE THREAD

**Issue by andreaswallberg** [Xinglab/TideHunter#9]
Dear TideHunter developers,

I am running this tool across sequences which have Ns in them to indicate gaps or ambiguous bases. It seems TideHunter treat these as regular symbols and annotate runs of "N" as repeats.

Is it possible to update the code to skip annotating Ns?

Can I use some other symbol to indicate positions that I do not want to have annotated?

**Comment by yangao07** [comment]
Hi,

TideHunter was initially developed for the sequencing data, which usually do not contain Ns, so we did not consider this.
This is acctually an easy update to skip those Ns.
I will let you know when it is done.

Yan

**Comment by andreaswallberg** [comment]
Thanks! That would be great!

I realize the main use-case is for raw data.

But the tool is so efficient and easy to use for finding tandem repeats, with easy to parse output, that I have actually used it also for contigs and scaffolds in an assembly.

Is there any particular reasons for why it should not be used for consensus sequences in an assembly or special considerations to make?

**Comment by yangao07** [comment]
Actually, no special considerations needed when running it on consensus sequences.
Just want to mention that TideHunter has lower sensitivity for very short tandem repeats (<100 bp) than other tools, e.g. TRF.

**Comment by yangao07** [comment]
Hi, please try out the latest commit, see if it skips the N bases in your sequences.

**Comment by andreaswallberg** [comment]
It works great! Thanks!
